name: Daily X Post

on:
  schedule:
    # Runs at 9 AM UTC every day
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env file
      run: |
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
        echo "TWITTER_APP_KEY=${{ secrets.TWITTER_APP_KEY }}" >> .env
        echo "TWITTER_APP_SECRET=${{ secrets.TWITTER_APP_SECRET }}" >> .env
        echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
        echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env
        
    - name: Post to X
      run: npm run dev -- "daily developer tip"
      
    - name: Post raw message (alternative)
      run: npm run dev -- --raw "Automated daily post from GitHub Actions! 🚀"
      continue-on-error: true 